version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: aws-partitions
    versions:
    - 1.437.0
    - 1.438.0
    - 1.440.0
    - 1.441.0
    - 1.442.0
    - 1.443.0
  - dependency-name: httpx
    versions:
    - 0.13.1
  - dependency-name: rubocop
    versions:
    - 1.10.0
  - dependency-name: regexp_parser
    versions:
    - 2.1.1
  - dependency-name: timers
    versions:
    - 4.3.3
