default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: rails_6_rss_reader_development
  username: rails_6_rss_reader_dev
  password: rails_6_rss_reader_pass

test: &test
  <<: *default
  host: localhost
  database: rails_6_rss_reader_test
  username: rails_6_rss_reader_dev
  password: rails_6_rss_reader_pass

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
