name: reviewdog
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
jobs:
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: test
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      - uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-check
          rubocop_extensions: rubocop-capybara:gemfile rubocop-factory_bot:gemfile rubocop-performance:gemfile rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-rspec_rails:gemfile
          rubocop_version: gemfile
          skip_install: false
          use_bundler: true
